name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run dependency updates
        run: |
         
          npm update

      - name: Create pull request
        run: |
         
          git checkout -b update-dependencies
          git add package.json package-lock.json
          git commit -m "Update dependencies"
          git push origin update-dependencies

      - name: Run tests
        run: |
        
          npm test
